[package]
name = "telemetry"
version.workspace = true
edition.workspace = true

[dependencies]
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json", "registry"] }
service-errors.workspace = true
thiserror.workspace = true
serde_json.workspace = true
rand.workspace = true
url.workspace = true
reqwest = { workspace = true, features = ["blocking", "rustls"] }

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
prost = "0.14.4"
opentelemetry-proto = { version = "0.32.0", default-features = false, features = ["gen-tonic-messages", "trace"] }
