[package]
name = "errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror= "1.0.33"

tonic= "0.8.0"
jsonwebtoken={ version = "8.1.1", optional = true }
