[package]
name = "errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror= "1.0.31"

tonic= "0.7.2"
jsonwebtoken={ version = "8.1.0", optional = true }
