name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - suxiaoshao
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product has a problem?
      options:
        - auth
        - login
        - collections
        - bookmarks
        - others
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component has a problem?
      options:
        - BE
        - FE
        - DB
        - devops
        - docs
    validations:
      required: true
  - type: textarea
    id: precondition
    attributes:
      label: Precondition
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: actual_results
    attributes:
      label: Actual results
    validations:
      required: true
  - type: textarea
    id: expected_results
    attributes:
      label: Expected results
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: zsh
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
