name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature"]
assignees:
  - suxiaoshao
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product has a feature request?
      options:
        - auth
        - login
        - collections
        - bookmarks
        - others
    validations:
      required: true
  - type: checkboxes
    id: component
    attributes:
      label: Component
      description: Which component has a feature request?
      options:
        - label: BE
        - label: FE
        - label: DB
        - label: devops
        - label: docs
  - type: textarea
    id: requirement
    attributes:
      label: Requirement
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
