[workspace]

members = [
    "packages/bookmarks",
    "packages/auth",
    "common/proto",
    "packages/login",
    "common/errors",
    "common/novel_crawler",
    "packages/collections",
    "common/middleware"
]
[profile.release]
strip = "symbols"