version: "3.9"
services:
  web:
    image: suxiaoshao/web:latest
    ports:
      - "80:80"
    restart: always
    container_name: web
    volumes:
      - /etc/nginx:/etc/nginx
  postgres:
    image: suxiaoshao/postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: postgres
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
volumes:
  postgres:
    name: postgres
