version: '3.9'
services:
  web:
    image: suxiaoshao/web:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    container_name: web
    volumes:
      - /private/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /private/etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - login
      - bookmarks
      - collections
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres
    env_file:
      - .env
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
  auth:
    image: suxiaoshao/auth:latest
    restart: always
    container_name: auth
    depends_on:
      - postgres
    env_file:
      - .env
  login:
    image: suxiaoshao/login:latest
    restart: always
    container_name: login
    depends_on:
      - auth
  bookmarks:
    image: suxiaoshao/bookmarks:latest
    restart: always
    container_name: bookmarks
    depends_on:
      - auth
      - postgres
    env_file:
      - .env
  collections:
    image: suxiaoshao/collections:latest
    restart: always
    container_name: collections
    depends_on:
      - auth
      - postgres
    env_file:
      - .env
volumes:
  postgres:
    name: postgres
