// Existing product language support; dependencies and aliases come from Prism metadata.
export const languages = [
  'clike',
  'markup-templating',
  'nginx',
  'typescript',
  'bash',
  'python',
  'sass',
  'css',
  'markdown',
  'markup',
  'go',
  'jsx',
  'tsx',
  'javascript',
  'yaml',
  'ejs',
  'java',
  'json',
  'nasm',
  'sql',
  'rust',
];
