name: auth-docker-build
on:
  push:
    branches:
      - main
    paths:
      - docker/packages/auth.Dockerfile
      - docker/packages/.cargo/**
      - server/packages/auth/**
      - server/common/errors/**
      - server/common/proto/**
      - .github/workflows/auth.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: suxiaoshao/auth:latest
          file: ./docker/packages/auth.Dockerfile
          context: .
