name: login-docker-build
on:
  push:
    branches:
      - main
    paths:
      - docker/packages/login.Dockerfile
      - server/packages/login/**
      - server/common/**
      - server/.cargo/**
      - .github/workflows/login.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: suxiaoshao/login:latest
          file: ./docker/packages/login.Dockerfile
          context: .
