name: web_test
on:
  pull_request:
    paths:
      - web/**
      - .github/workflows/web_test.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
