schema: schema.graphql
extensions:
  endpoints:
    GraphQL schema:
      url: https://bookmarks.sushao.top/graphql
      headers:
        Authorization: ${AUTH_TOKEN_ENV}
        user-agent: JS GraphQL
      introspect: false
